# Generated by Django 5.1.2 on 2025-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fedcode", "0005_remove_person_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="package",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
