name: CI Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure env
        run:  make dev && ./configure --docs

      - name: Check Sphinx Documentation build minimally
        run: make docs

      - name: Check for documentation style errors
        working-directory: ./docs
        run: ./scripts/doc8_style_check.sh


